steps:
  # Step 1: Install dependencies
  - name: node
    entrypoint: npm
    args: ['install']

  # Step 2: Build React Native project
  - name: node
    entrypoint: npx
    args: ['react-native','react-native asset', 'bundle', '--platform', 'android', '--dev', 'false', '--entry-file', 'index.js', '--bundle-output', 'android/app/src/main/assets/index.android.bundle', '--assets-dest', 'android/app/src/main/res']
  - run: npx react-native asset    
  - run: cd android && ./gradlew clean
     